# Generated by Django 5.0.1 on 2024-01-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('monthly_salary', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('approved_limit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loan_data',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emis_paid_on_time', models.IntegerField()),
                ('date_of_approval', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.customer_data')),
            ],
        ),
    ]
